# Generated by Django 2.1.3 on 2019-03-31 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredeints',
            new_name='ingredients',
        ),
    ]
